name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v6
    
    - name: Install Ubuntu requirements
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get -y install autoconf automake bison flex gcc libelf-dev make texinfo libncurses5-dev patch python3 python-is-python3 subversion wget zlib1g-dev libtool-bin python3-dev bzip2 libgmp3-dev pkg-config

    - name: Runs all the stages in the shell
      run: |
        mkdir $PWD/ps3dev
        export PS3DEV=$PWD/ps3dev
        export PSL1GHT=$PS3DEV
        export PATH=$PATH:$PS3DEV/bin
        export PATH=$PATH:$PS3DEV/ppu/bin
        export PATH=$PATH:$PS3DEV/spu/bin
        ./toolchain.sh

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    
    - name: Compress ps3dev folder
      run: |
        tar -zcvf ps3dev.tar.gz ps3dev

    - uses: actions/upload-artifact@v6
      with:
        name: ps3dev-${{ steps.slug.outputs.sha8 }}-${{matrix.os}}
        path: ps3dev.tar.gz
