name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  ShellCheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ShellCheck Depends
        uses: ludeeus/action-shellcheck@master
  Docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: ShellCheck
    steps:
      - name: Make Space
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Checkout
        if: success()
        id: checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        if: success()
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: success()
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo ::set-output name=docker_platforms::linux/amd64,linux/386
          VERSION_TAG=${GITHUB_REF#refs/*/}
          echo ::set-output name=version::${VERSION_TAG%/merge}
#      - name: Login to DockerHub
#        if: success()
#        id: login_docker
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        if: success()
        id: login_github
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (master)
        if: success() && steps.prepare.outputs.version == 'master' && github.event_name != 'pull_request'
        id: build_push_master
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ steps.prepare.outputs.docker_platforms }}
          push: true
          tags: |
            ghcr.io/ps3dev/ps3dev:master
            ghcr.io/ps3dev/ps3dev:latest
#            ps3dev/ps3dev:master
#            ps3dev/ps3dev:latest
      - name: Build and push (development)
        if: success() && steps.prepare.outputs.version != 'master'
        id: build_push_development
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ steps.prepare.outputs.docker_platforms }}
          push: true
          tags: |
            ghcr.io/ps3dev/ps3dev:${{ steps.prepare.outputs.version }}
#            ps3dev/ps3dev:${{ steps.prepare.outputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        if: success()
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
