name: ci

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: [x64]
    defaults:
      run:
        shell: bash

    outputs:
      sha8: ${{ steps.slug.outputs.sha8 }}
      date: ${{ steps.date.outputs.date }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Set up Docker Buildx
      if: success()
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Prepare
      if: success()
      id: prepare
      run: |
        sudo apt update
        sudo apt -y install autoconf automake bison flex gcc g++ libelf-dev make texinfo libncurses5-dev patch python2-dev subversion wget zlib1g-dev libtool-bin python-dev-is-python3 bzip2 libgmp3-dev pkg-config libssl-dev && \
        if [ "$(uname -m)" = "x86_64" ]; then sudo apt install -y nvidia-cg-toolkit ; fi
    
    - name: Install macOS requirements
      if: startsWith(matrix.os, 'macos')
      # act -P macos-latest=-self-hosted --container-architecture linux/amd64
      run: |
        echo "${GITHUB_PASSWORD}" | docker login --username "${{ steps.prepare.outputs.docker_username }}" --password-stdin docker.pkg.github.com
        echo ::set-output name=buildx::$(echo docker buildx build --output type=image,name=${{ steps.prepare.outputs.github_image }},push=true \
          --platform ${{ steps.prepare.outputs.docker_platforms }} --cache-from "type=local,src=/tmp/.buildx-cache" --cache-to "type=local,dest=/tmp/.buildx-cache" \
          --tag "${{ steps.prepare.outputs.github_image }}:${{ steps.prepare.outputs.version }}")
    - name: Cache Docker layers
      uses: actions/cache@v5
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ steps.prepare.outputs.version }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Run Buildx (master)
      if: success() && steps.prepare.outputs.version == 'master' && github.event_name != 'pull_request'
      run: |
        . ~/.bashrc
        mkdir -p $PWD/ps3dev
        export PS3DEV=$PWD/ps3dev
        export PSL1GHT=$PS3DEV
        export PATH=$PATH:$PS3DEV/bin
        export PATH=$PATH:$PS3DEV/ppu/bin
        export PATH=$PATH:$PS3DEV/spu/bin
        export PATH=$PATH:$PS3DEV/portlibs/ppu/bin
        export PKG_CONFIG_PATH=$PS3DEV/portlibs/ppu/lib/pkgconfig
        ./toolchain.sh

    - name: Compress ps3dev folder
      run: |
        tar -zcvf ps3dev-${{matrix.os}}-${{steps.arch.outputs.arch}}-${{steps.date.outputs.date}}.tar.gz ps3dev

    - name: Archive Folder
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.os}}-${{matrix.architecture}}
        path: ps3dev-*.tar.gz

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all Artifact
        uses: actions/download-artifact@v4

      - name: Set SemVer
        id: semver
        run: echo "::set-output name=semver::0.1.0+${{ needs.build.outputs.date }}.${{ needs.build.outputs.sha8 }}"
  
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.semver.outputs.semver }}
          message: "automatic tag creation"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.semver.outputs.semver }}
          files: |
            ${{ github.workspace }}/**/*.tar.gz
            
